### ISSUE TITLE
CDP as HTTP request

### ISSUE THREAD

**Issue by red-erik** [micelshima/PKInotify#1]
Hello,
thank you for your work and for sharing.
I'm trying to configure it in my env but we only have CDP reachable through http request.
Your script gives "Item not found".
Do you have any suggestion ?

Regards,
Red.

**Comment by micelshima** [comment]
in line 92 of pkinotifyCLI.ps1 I have added this code, but didn't tested yet:
if($_.cdp -match "^http" -and $_.cdp -match "crl$"){
		$CRLfiles=""|select name,fullname
		$CRLfiles.name=split-path $_.cdp -leaf
		CRLfiles.fullname="$($env:temp)\$($CRLfiles.name)"
		$null=invoke-webrequest $_.cdp -outfile CRLfiles.fullname
	}
	elseif($_.cdp -match "\\\\"){$CRLfiles = get-childitem "$($_.cdp)\*.crl"}
